export const ALL_BLOG_REQUEST = "ALL_BLOG_REQUEST";
export const  ALL_BLOG_SUCCESS = " ALL_BLOG_SUCCESS ";
export const ALL_BLOG_FAIL = " ALL_BLOG_FAIL";


export const CREATE_BLOG_REQUEST = "CREATE_BLOG_REQUEST";
export const CREATE_BLOG_SUCCESS ="CREATE_BLOG_SUCCESS";
export const CREATE_BLOG_FAIL = "CREATE_BLOG_FAIL";
export const CREATE_BLOG_RESET = "CREATE_BLOG_RESET";


export const DELETE_BLOG_REQUEST = "DELETE_BLOG_REQUEST";
export const DELETE_BLOG_SUCCESS ="DELETE_BLOG_SUCCESS";
export const DELETE_BLOG_FAIL = "DELETE_BLOG_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";