export const ALL_CONTACT_REQUEST = "ALL_CONTACT_REQUEST";
export const  ALL_CONTACT_SUCCESS = " ALL_CONTACT_SUCCESS ";
export const ALL_CONTACT_FAIL = " ALL_CONTACT_FAIL";

export const CREATE_CONTACT_REQUEST ="CREATE_CONTACT_REQUEST";
export const CREATE_CONTACT_SUCCESS ="CREATE_CONTACT_UPDATE";
export const CREATE_CONTACT_FAIL = "CREATE_CONTACT_FAIL";

export const CLEAR_ERRORS = "CLEAR_ERRORS";