export const ALL_EXPERTISE_REQUEST = "ALL_EXPERTISE_REQUEST";
export const  ALL_EXPERTISE_SUCCESS = " ALL_EXPERTISE_SUCCESS ";
export const ALL_EXPERTISE_FAIL = " ALL_EXPERTISE_FAIL";

export const CREATE_EXPERTISE_REQUEST = "CREATE_EXPERTISE_REQUEST"
export const CREATE_EXPERTISE_SUCCESS="CREATE_EXPERTISSE_SUCCESS"
export const CREATE_EXPERTISE_FAIL ="CREATE_EXPERTISE_FAIL"
export const CLEAR_ERRORS = "CLEAR_ERRORS";
