export const ALL_FEEDBACK_REQUEST = "ALL_FEEDBACK_REQUEST";
export const  ALL_FEEDBACK_SUCCESS = " ALL_FEEDBACK_SUCCESS ";
export const ALL_FEEDBACK_FAIL = " ALL_FEEDBACK_FAIL";

export const CREATE_FEEDBACK_REQUEST = "CREATE_FEEDBACK_REQUEST";
export const CREATE_FEEDBACK_SUCCESS ="CREATE_FEEDBACK_SUCCESS";
export const CREATE_FEEDBACK_FAIL = "CREATE_FEEDBACK_FAIL";

export const DELETE_FEEDBACK_REQUEST = "DELETE_FEEDBACK_REQUEST"
export const DELETE_FEEDBACK_SUCCESS ="DELETE_FEEDBACK_SUCCESS"
export const DELETE_FEEDBACK_FAIL ="DELETE_FEEDBACK_FAIL"

export const CLEAR_ERRORS = "CLEAR_ERRORS";