export const ALL_GALLERY_REQUEST = "ALL_GALLERY_REQUEST";
export const  ALL_GALLERY_SUCCESS = " ALL_GALLERY_SUCCESS ";
export const ALL_GALLERY_FAIL = " ALL_GALLERY_FAIL";
export const CLEAR_ERRORS = "CLEAR_ERRORS";

export const CREATE_GALLERY_REQUEST = "CREATE_GALLERY_REQUEST";
export const CREATE_GALLERY_SUCCESS = "CREATE_GALLERY_SUCCESS";
export const CREATE_GALLERY_FAIL = "CREATE_GALLERY_FAIL";


export const UPDATE_GALLERY_REQUEST = "UPDATE_GALLERY_REQUEST"
export const UPDATE_GALLERY_SUCCESS = "UPDATE_GALLERY_SUCCESS";
export const UPDATE_GALLERY_FAIL = "UPDATE_GALLERY_FAIL";

export const DELETE_GALLERY_REQUEST = "DELETE_GALLERY_REQUEST";
export const DELETE_GALLERY_SUCCESS = "DELETE_GALLERY_SUCCESS";

export const DELETE_GALLERY_FAIL = "DELETE_GALLERY_FAIL";